In [161]:
#svm with just one variable

In [162]:
import numpy as np
import pandas as pd
from copy import deepcopy
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.svm import SVC

def median(data):
    data=deepcopy(data)
    N=len(data)
    if N//2:
        median=(data[N//2+1]+data[N//2])/2
    else:
        median=(data[(N+1)//2])
    return median

def M(data,k): #kth central moment
    # central moments has lots of use,
    # for example: (--> means related to)
    # k=0-->total
    # k=1-->mean, k=2-->variance
    # k=3-->skewness, k=4-->kurtosis
    data=deepcopy(data)
    Mk=0
    for i in data:
        Mk+=(i)**k
    return Mk

file_name=r"C:\Users\chius\OneDrive\codes\python codes\ml codes\Example to Classification.csv"
df = pd.read_csv(file_name)
df_init=df.head(200)[df['Country']=='UK']
#df_init=df
N=df_init.shape[0]

print(df_init)

            Sales Person Country               Product        Date  \
0         Jehu Rudeforth      UK       Mint Chip Choco  04/01/2022
4         Jehu Rudeforth      UK   Peanut Butter Cubes  24/02/2022
6             Oby Sorrel      UK       99% Dark & Pure  25/01/2022
10   Rafaelita Blaksland      UK    Smooth Sliky Salty  13/01/2022
19        Curtice Advani      UK         85% Dark Bars  08/06/2022
23          Husein Augar      UK         Drinking Coco  14/03/2022
31   Rafaelita Blaksland      UK       99% Dark & Pure  29/06/2022
33      Karlen McCaffrey      UK          Almond Choco  30/06/2022
36        Andria Kimpton      UK        50% Dark Bites  24/08/2022
71          Gigi Bohling      UK          Almond Choco  10/01/2022
74           Van Tuxwell      UK   Organic Choco Syrup  26/08/2022
78           Van Tuxwell      UK       99% Dark & Pure  31/01/2022
90   Dennison Crosswaite      UK               Eclairs  24/03/2022
97         Kelci Walkden      UK      Fruit & Nut Bars  29/06/2022
106         Husein Augar      UK   Spicy Special Slims  25/08/2022
111        Kelci Walkden      UK    Smooth Sliky Salty  19/01/2022
124        Kelci Walkden      UK               Eclairs  25/01/2022
126       Dotty Strutley      UK          Almond Choco  28/07/2022
133          Van Tuxwell      UK             Milk Bars  25/07/2022
138         Ches Bonnell      UK    Smooth Sliky Salty  11/07/2022
152          Kaine Padly      UK   Organic Choco Syrup  31/03/2022
154     Karlen McCaffrey      UK               Eclairs  25/01/2022
156         Gigi Bohling      UK           After Nines  29/03/2022
165       Marney O'Breen      UK  Caramel Stuffed Bars  19/07/2022
172          Brien Boise      UK            White Choc  12/04/2022
175     Karlen McCaffrey      UK   Baker's Choco Chips  07/02/2022
178           Oby Sorrel      UK  Choco Coated Almonds  17/03/2022
185       Camilla Castle      UK            White Choc  03/01/2022
187       Dotty Strutley      UK       99% Dark & Pure  03/01/2022
189         Barr Faughny      UK        50% Dark Bites  28/01/2022
191         Husein Augar      UK  Choco Coated Almonds  02/03/2022
197  Dennison Crosswaite      UK            White Choc  03/08/2022

            Amount  Boxes Shipped
0     US$5,320.00             180
4    US$13,685.00             184
6    US$13,685.00             176
10    US$4,704.00              62
19    US$1,085.00             172
23    US$3,003.00             113
31   US$12,446.00             150
33    US$6,839.00             133
36    US$2,653.00             314
71    US$5,642.00               9
74    US$2,002.00             214
78    US$4,725.00             137
90    US$6,188.00             270
97   US$13,006.00             482
106   US$4,697.00              42
111   US$5,929.00             175
124   US$4,606.00              57
126  US$16,114.00              96
133   US$4,263.00              90
138   US$5,663.00             110
152   US$2,282.00             178
154   US$7,798.00             196
156   US$8,029.00             175
165   US$3,549.00             112
172   US$5,299.00             167
175   US$4,753.00             389
178   US$9,324.00              41
185   US$9,982.00             187
187   US$9,310.00             282
189     US$581.00              65
191   US$4,333.00              43
197   US$7,238.00             265

C:\Users\chius\AppData\Local\Temp\ipykernel_29636\3547435686.py:31: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_init=df.head(200)[df['Country']=='UK']

In [163]:
df['Country'].value_counts()

Country
Australia      615
India          552
USA            537
UK             534
Canada         525
New Zealand    519
Name: count, dtype: int64

In [164]:
# possible questions
# Can we guess which country a sale happened in based on the product and the volume shipped?
# Can we predict which type of chocolate was sold?
# We could create a new label (e.g., "High" vs "Low") based on the Amount or Boxes Shipped?

In [165]:
df_init['Amount'] = df_init['Amount'].str.replace('US$', '', regex=False) \
                                     .str.replace(',', '', regex=False) \
                                     .str.strip() \
                                     .astype(float)
df_init

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,5320.0,180
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,13685.0,184
6,Oby Sorrel,UK,99% Dark & Pure,25/01/2022,13685.0,176
10,Rafaelita Blaksland,UK,Smooth Sliky Salty,13/01/2022,4704.0,62
19,Curtice Advani,UK,85% Dark Bars,08/06/2022,1085.0,172
23,Husein Augar,UK,Drinking Coco,14/03/2022,3003.0,113
31,Rafaelita Blaksland,UK,99% Dark & Pure,29/06/2022,12446.0,150
33,Karlen McCaffrey,UK,Almond Choco,30/06/2022,6839.0,133
36,Andria Kimpton,UK,50% Dark Bites,24/08/2022,2653.0,314
71,Gigi Bohling,UK,Almond Choco,10/01/2022,5642.0,9
74,Van Tuxwell,UK,Organic Choco Syrup,26/08/2022,2002.0,214
78,Van Tuxwell,UK,99% Dark & Pure,31/01/2022,4725.0,137
90,Dennison Crosswaite,UK,Eclairs,24/03/2022,6188.0,270
97,Kelci Walkden,UK,Fruit & Nut Bars,29/06/2022,13006.0,482
106,Husein Augar,UK,Spicy Special Slims,25/08/2022,4697.0,42
111,Kelci Walkden,UK,Smooth Sliky Salty,19/01/2022,5929.0,175
124,Kelci Walkden,UK,Eclairs,25/01/2022,4606.0,57
126,Dotty Strutley,UK,Almond Choco,28/07/2022,16114.0,96
133,Van Tuxwell,UK,Milk Bars,25/07/2022,4263.0,90
138,Ches Bonnell,UK,Smooth Sliky Salty,11/07/2022,5663.0,110
152,Kaine Padly,UK,Organic Choco Syrup,31/03/2022,2282.0,178
154,Karlen McCaffrey,UK,Eclairs,25/01/2022,7798.0,196
156,Gigi Bohling,UK,After Nines,29/03/2022,8029.0,175
165,Marney O'Breen,UK,Caramel Stuffed Bars,19/07/2022,3549.0,112
172,Brien Boise,UK,White Choc,12/04/2022,5299.0,167
175,Karlen McCaffrey,UK,Baker's Choco Chips,07/02/2022,4753.0,389
178,Oby Sorrel,UK,Choco Coated Almonds,17/03/2022,9324.0,41
185,Camilla Castle,UK,White Choc,03/01/2022,9982.0,187
187,Dotty Strutley,UK,99% Dark & Pure,03/01/2022,9310.0,282
189,Barr Faughny,UK,50% Dark Bites,28/01/2022,581.0,65
191,Husein Augar,UK,Choco Coated Almonds,02/03/2022,4333.0,43
197,Dennison Crosswaite,UK,White Choc,03/08/2022,7238.0,265

In [166]:
Season={'Date':{'1':4,'2':4,'3':1,'4':1,'5':1,'6':2,
        '7':2,'8':2,'9':3,'10':3,'11':3,'12':4}}

df_init['Date']=pd.to_datetime(df_init['Date'],dayfirst=True)
df_init['Date']=df_init['Date'].dt.month
df_init=df_init.replace(Season).infer_objects(copy=False)
df_init

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,1,5320.0,180
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2,13685.0,184
6,Oby Sorrel,UK,99% Dark & Pure,1,13685.0,176
10,Rafaelita Blaksland,UK,Smooth Sliky Salty,1,4704.0,62
19,Curtice Advani,UK,85% Dark Bars,6,1085.0,172
23,Husein Augar,UK,Drinking Coco,3,3003.0,113
31,Rafaelita Blaksland,UK,99% Dark & Pure,6,12446.0,150
33,Karlen McCaffrey,UK,Almond Choco,6,6839.0,133
36,Andria Kimpton,UK,50% Dark Bites,8,2653.0,314
71,Gigi Bohling,UK,Almond Choco,1,5642.0,9
74,Van Tuxwell,UK,Organic Choco Syrup,8,2002.0,214
78,Van Tuxwell,UK,99% Dark & Pure,1,4725.0,137
90,Dennison Crosswaite,UK,Eclairs,3,6188.0,270
97,Kelci Walkden,UK,Fruit & Nut Bars,6,13006.0,482
106,Husein Augar,UK,Spicy Special Slims,8,4697.0,42
111,Kelci Walkden,UK,Smooth Sliky Salty,1,5929.0,175
124,Kelci Walkden,UK,Eclairs,1,4606.0,57
126,Dotty Strutley,UK,Almond Choco,7,16114.0,96
133,Van Tuxwell,UK,Milk Bars,7,4263.0,90
138,Ches Bonnell,UK,Smooth Sliky Salty,7,5663.0,110
152,Kaine Padly,UK,Organic Choco Syrup,3,2282.0,178
154,Karlen McCaffrey,UK,Eclairs,1,7798.0,196
156,Gigi Bohling,UK,After Nines,3,8029.0,175
165,Marney O'Breen,UK,Caramel Stuffed Bars,7,3549.0,112
172,Brien Boise,UK,White Choc,4,5299.0,167
175,Karlen McCaffrey,UK,Baker's Choco Chips,2,4753.0,389
178,Oby Sorrel,UK,Choco Coated Almonds,3,9324.0,41
185,Camilla Castle,UK,White Choc,1,9982.0,187
187,Dotty Strutley,UK,99% Dark & Pure,1,9310.0,282
189,Barr Faughny,UK,50% Dark Bites,1,581.0,65
191,Husein Augar,UK,Choco Coated Almonds,3,4333.0,43
197,Dennison Crosswaite,UK,White Choc,8,7238.0,265